# ============================================================
# Portal Noticias — Application Configuration
# ============================================================

# Server
server.port=8080

# JDBC
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=USR_NOTICIAS
spring.datasource.password=Noticias192026$
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration


logging.level.com.zaxxer.hikari=INFO
logging.level.org.springframework.jdbc=DEBUG
