-- ============================================================
-- ProyectoFinal News Portal — Schema Setup
-- Script: 01_schema.sql
-- Schema: USR_NOTICIAS
-- Run as: USR_NOTICIAS user in SQL*Plus or SQL Developer
-- ============================================================

-- ------------------------------------------------------------
-- Drop existing objects (safe re-run)
-- ------------------------------------------------------------

BEGIN EXECUTE IMMEDIATE 'DROP TABLE CALIFICACIONES CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COMENTARIOS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NOTICIAS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUBTEMAS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TEMAS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIOS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TEMAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SUBTEMAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NOTICIAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COMENTARIOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CALIFICACIONES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
-- SEQUENCES
-- ============================================================

CREATE SEQUENCE SEQ_USUARIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/

CREATE SEQUENCE SEQ_TEMAS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/

CREATE SEQUENCE SEQ_SUBTEMAS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/

CREATE SEQUENCE SEQ_NOTICIAS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/

CREATE SEQUENCE SEQ_COMENTARIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/

CREATE SEQUENCE SEQ_CALIFICACIONES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/

-- ============================================================
-- TABLES
-- ============================================================

-- 1a. USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO  NUMBER(10)    NOT NULL,
    NOMBRE      VARCHAR2(100) NOT NULL,
    APELLIDOS   VARCHAR2(100) NOT NULL,
    EMAIL       VARCHAR2(150) NOT NULL,
    PASSWORD    VARCHAR2(16)  NOT NULL,
    ROL         VARCHAR2(10)  NOT NULL,
    ACTIVO      NUMBER(1)     DEFAULT 1 NOT NULL,
    CONSTRAINT PK_USUARIOS     PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_USUARIOS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USUARIOS_ROL  CHECK (ROL IN ('LECTOR', 'AUTOR', 'ADMIN')),
    CONSTRAINT CK_USUARIOS_ACTIVO CHECK (ACTIVO IN (0, 1))
);
/

-- 1b. TEMAS
CREATE TABLE TEMAS (
    ID_TEMA     NUMBER(10)    NOT NULL,
    NOMBRE      VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_TEMAS PRIMARY KEY (ID_TEMA)
);
/

-- 1c. SUBTEMAS
CREATE TABLE SUBTEMAS (
    ID_SUBTEMA  NUMBER(10)    NOT NULL,
    NOMBRE      VARCHAR2(100) NOT NULL,
    ID_TEMA     NUMBER(10)    NOT NULL,
    CONSTRAINT PK_SUBTEMAS    PRIMARY KEY (ID_SUBTEMA),
    CONSTRAINT FK_SUBTEMAS_TEMA FOREIGN KEY (ID_TEMA) REFERENCES TEMAS(ID_TEMA)
);
/

-- 1d. NOTICIAS
CREATE TABLE NOTICIAS (
    ID_NOTICIA            NUMBER(10)    NOT NULL,
    TITULO                VARCHAR2(300) NOT NULL,
    CUERPO                CLOB          NOT NULL,
    ESTADO                VARCHAR2(15)  DEFAULT 'BORRADOR' NOT NULL,
    FECHA_CREACION        DATE          DEFAULT SYSDATE NOT NULL,
    FECHA_PUBLICACION     DATE,
    PROMEDIO_CALIFICACION NUMBER(3,2)   DEFAULT 0,
    ID_AUTOR              NUMBER(10)    NOT NULL,
    ID_TEMA               NUMBER(10)    NOT NULL,
    ID_SUBTEMA            NUMBER(10)    NOT NULL,
    CONSTRAINT PK_NOTICIAS      PRIMARY KEY (ID_NOTICIA),
    CONSTRAINT FK_NOTICIAS_AUTOR  FOREIGN KEY (ID_AUTOR)    REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_NOTICIAS_TEMA   FOREIGN KEY (ID_TEMA)     REFERENCES TEMAS(ID_TEMA),
    CONSTRAINT FK_NOTICIAS_SUBTEMA FOREIGN KEY (ID_SUBTEMA) REFERENCES SUBTEMAS(ID_SUBTEMA),
    CONSTRAINT CK_NOTICIAS_ESTADO CHECK (ESTADO IN ('BORRADOR', 'PUBLICADO', 'ARCHIVADO'))
);
/

-- 1e. COMENTARIOS
CREATE TABLE COMENTARIOS (
    ID_COMENTARIO   NUMBER(10)    NOT NULL,
    CONTENIDO       VARCHAR2(2000) NOT NULL,
    FECHA_COMENTARIO DATE          DEFAULT SYSDATE NOT NULL,
    ID_NOTICIA      NUMBER(10)    NOT NULL,
    ID_USUARIO      NUMBER(10)    NOT NULL,
    CONSTRAINT PK_COMENTARIOS       PRIMARY KEY (ID_COMENTARIO),
    CONSTRAINT FK_COMENTARIOS_NOTICIA FOREIGN KEY (ID_NOTICIA) REFERENCES NOTICIAS(ID_NOTICIA),
    CONSTRAINT FK_COMENTARIOS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
/

-- 1f. CALIFICACIONES
CREATE TABLE CALIFICACIONES (
    ID_CALIFICACION  NUMBER(10) NOT NULL,
    VALOR            NUMBER(1)  NOT NULL,
    FECHA_CALIFICACION DATE     DEFAULT SYSDATE NOT NULL,
    ID_NOTICIA       NUMBER(10) NOT NULL,
    ID_USUARIO       NUMBER(10) NOT NULL,
    CONSTRAINT PK_CALIFICACIONES         PRIMARY KEY (ID_CALIFICACION),
    CONSTRAINT UQ_CALIF_USUARIO_NOTICIA  UNIQUE (ID_NOTICIA, ID_USUARIO),
    CONSTRAINT FK_CALIFICACIONES_NOTICIA  FOREIGN KEY (ID_NOTICIA) REFERENCES NOTICIAS(ID_NOTICIA),
    CONSTRAINT FK_CALIFICACIONES_USUARIO  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT CK_CALIFICACIONES_VALOR    CHECK (VALOR BETWEEN 1 AND 5)
);
/

-- ============================================================
-- Verification queries (run manually to confirm)
-- SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;
-- SELECT SEQUENCE_NAME FROM USER_SEQUENCES ORDER BY SEQUENCE_NAME;
-- SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME='CALIFICACIONES';
-- ============================================================

COMMIT;
/
