-- ============================================================
-- ProyectoFinal News Portal — Views (10 required)
-- Script: 13_views.sql
-- ============================================================

-- 1. VW_NOTICIAS_PUBLICADAS
-- All published articles with tema/subtema/autor info
CREATE OR REPLACE VIEW VW_NOTICIAS_PUBLICADAS AS
    SELECT N.ID_NOTICIA,
           N.TITULO,
           PKG_UTILES.FN_TRUNCAR_TEXTO(N.TITULO, 100)          AS TITULO_CORTO,
           N.CUERPO,
           N.FECHA_PUBLICACION,
           PKG_UTILES.FN_FORMATEAR_FECHA(N.FECHA_PUBLICACION)  AS FECHA_FORMATEADA,
           N.PROMEDIO_CALIFICACION,
           T.ID_TEMA,
           T.NOMBRE      AS NOMBRE_TEMA,
           S.ID_SUBTEMA,
           S.NOMBRE      AS NOMBRE_SUBTEMA,
           U.ID_USUARIO  AS ID_AUTOR,
           U.NOMBRE || ' ' || U.APELLIDOS AS NOMBRE_AUTOR
      FROM NOTICIAS N
      JOIN TEMAS    T ON N.ID_TEMA    = T.ID_TEMA
      JOIN SUBTEMAS S ON N.ID_SUBTEMA = S.ID_SUBTEMA
      JOIN USUARIOS U ON N.ID_AUTOR   = U.ID_USUARIO
     WHERE N.ESTADO = 'PUBLICADO';
/

-- 2. VW_NOTICIAS_POR_AUTOR
-- All articles with autor name (any estado)
CREATE OR REPLACE VIEW VW_NOTICIAS_POR_AUTOR AS
    SELECT N.ID_NOTICIA,
           N.TITULO,
           N.ESTADO,
           N.FECHA_CREACION,
           N.FECHA_PUBLICACION,
           N.PROMEDIO_CALIFICACION,
           N.ID_AUTOR,
           U.NOMBRE || ' ' || U.APELLIDOS AS NOMBRE_AUTOR,
           T.NOMBRE AS NOMBRE_TEMA,
           S.NOMBRE AS NOMBRE_SUBTEMA
      FROM NOTICIAS N
      JOIN USUARIOS U ON N.ID_AUTOR   = U.ID_USUARIO
      JOIN TEMAS    T ON N.ID_TEMA    = T.ID_TEMA
      JOIN SUBTEMAS S ON N.ID_SUBTEMA = S.ID_SUBTEMA;
/

-- 3. VW_COMENTARIOS_POR_NOTICIA
-- Comments with author name and article title
CREATE OR REPLACE VIEW VW_COMENTARIOS_POR_NOTICIA AS
    SELECT C.ID_COMENTARIO,
           C.CONTENIDO,
           C.FECHA_COMENTARIO,
           C.ID_NOTICIA,
           N.TITULO AS TITULO_NOTICIA,
           C.ID_USUARIO,
           U.NOMBRE || ' ' || U.APELLIDOS AS NOMBRE_AUTOR
      FROM COMENTARIOS C
      JOIN NOTICIAS N ON C.ID_NOTICIA = N.ID_NOTICIA
      JOIN USUARIOS U ON C.ID_USUARIO = U.ID_USUARIO;
/

-- 4. VW_CALIFICACIONES_POR_NOTICIA
-- Ratings with author name and article title
CREATE OR REPLACE VIEW VW_CALIFICACIONES_POR_NOTICIA AS
    SELECT CA.ID_CALIFICACION,
           CA.VALOR,
           CA.FECHA_CALIFICACION,
           CA.ID_NOTICIA,
           N.TITULO AS TITULO_NOTICIA,
           CA.ID_USUARIO,
           U.NOMBRE || ' ' || U.APELLIDOS AS NOMBRE_AUTOR
      FROM CALIFICACIONES CA
      JOIN NOTICIAS N ON CA.ID_NOTICIA = N.ID_NOTICIA
      JOIN USUARIOS U ON CA.ID_USUARIO = U.ID_USUARIO;
/

-- 5. VW_USUARIOS_ACTIVOS
-- Only active user accounts
CREATE OR REPLACE VIEW VW_USUARIOS_ACTIVOS AS
    SELECT ID_USUARIO, NOMBRE, APELLIDOS, EMAIL, ROL
      FROM USUARIOS
     WHERE ACTIVO = 1;
/

-- 6. VW_TEMAS_CON_SUBTEMAS
-- Temas with a count of their subtemas
CREATE OR REPLACE VIEW VW_TEMAS_CON_SUBTEMAS AS
    SELECT T.ID_TEMA,
           T.NOMBRE,
           T.DESCRIPCION,
           COUNT(S.ID_SUBTEMA) AS TOTAL_SUBTEMAS
      FROM TEMAS T
      LEFT JOIN SUBTEMAS S ON T.ID_TEMA = S.ID_TEMA
     GROUP BY T.ID_TEMA, T.NOMBRE, T.DESCRIPCION;
/

-- 7. VW_NOTICIAS_CON_AUTOR
-- All articles with full author name (all estados)
CREATE OR REPLACE VIEW VW_NOTICIAS_CON_AUTOR AS
    SELECT N.ID_NOTICIA,
           N.TITULO,
           N.ESTADO,
           N.FECHA_CREACION,
           N.FECHA_PUBLICACION,
           N.PROMEDIO_CALIFICACION,
           N.ID_AUTOR,
           U.NOMBRE || ' ' || U.APELLIDOS AS NOMBRE_AUTOR,
           N.ID_TEMA,
           N.ID_SUBTEMA
      FROM NOTICIAS N
      JOIN USUARIOS U ON N.ID_AUTOR = U.ID_USUARIO;
/

-- 8. VW_ESTADISTICAS_COMENTARIOS
-- Comment count grouped by article
CREATE OR REPLACE VIEW VW_ESTADISTICAS_COMENTARIOS AS
    SELECT N.ID_NOTICIA,
           N.TITULO,
           COUNT(C.ID_COMENTARIO) AS TOTAL_COMENTARIOS
      FROM NOTICIAS    N
      LEFT JOIN COMENTARIOS C ON N.ID_NOTICIA = C.ID_NOTICIA
     GROUP BY N.ID_NOTICIA, N.TITULO;
/

-- 9. VW_ESTADISTICAS_CALIFICACIONES
-- Average rating per article
CREATE OR REPLACE VIEW VW_ESTADISTICAS_CALIFICACIONES AS
    SELECT N.ID_NOTICIA,
           N.TITULO,
           N.PROMEDIO_CALIFICACION,
           COUNT(CA.ID_CALIFICACION) AS TOTAL_CALIFICACIONES
      FROM NOTICIAS       N
      LEFT JOIN CALIFICACIONES CA ON N.ID_NOTICIA = CA.ID_NOTICIA
     GROUP BY N.ID_NOTICIA, N.TITULO, N.PROMEDIO_CALIFICACION;
/

-- 10. VW_NOTICIAS_POR_ESTADO
-- Article count grouped by estado
CREATE OR REPLACE VIEW VW_NOTICIAS_POR_ESTADO AS
    SELECT ESTADO,
           COUNT(*) AS TOTAL_ARTICULOS
      FROM NOTICIAS
     GROUP BY ESTADO;
/
